include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
  exclude:
    - "**circuits_model.dart"
    - "**seasons_model.dart"
    - "**.g.dart"
    - "**.gr.dart"
