name: f1_pet_project
description: F1 pet project. State Management - Elementary. Navigation - Auto Route. API - http://ergast.com/mrd/.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  auto_route: ^7.8.4
  colorful_safe_area: ^1.0.0
  cookie_jar: ^4.0.8
  dartdoc: ^6.3.0 # do not update because of - analyzer from dark sdk
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_html: 3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  geolocator: ^10.1.1
  horizontal_data_table: ^4.3.1
  image: ^4.1.7
  intl: 0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  loading_animation_widget: ^1.2.0+4
  package_info_plus: ^8.3.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.1.1
  quiver: ^3.2.1
  responsive_framework: ^1.1.1
  scroll_to_index: ^3.0.1
  table_calendar: ^3.0.9
  url_launcher: ^6.2.4
  visibility_detector: ^0.4.0+2
  yandex_mapkit: ^3.4.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  elementary_test: ^2.0.0
  # flutter_native_splash: ^2.2.17
  # flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1

# flutter_icons:
#   android: "ic_launcher"
#   ios: false
#   image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/calendar/
    - assets/nav_bar/
    - assets/icons/

  fonts:
    - family: HelveticaNeueCyr
      fonts:
        - asset: fonts/HelveticaNeueCyr-Light.ttf

    - family: HelveticaNeueCyr-Bold
      fonts:
        - asset: fonts/HelveticaNeueCyr-Bold.ttf

    - family: HelveticaNeueCyr-Medium
      fonts:
        - asset: fonts/HelveticaNeueCyr-Medium.ttf

    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter-Regular.ttf
