name: f1_pet_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  colorful_safe_area: ^1.0.0
  cookie_jar: ^3.0.1
  # не обновлять дио, придется менять request handler
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  elementary: ^2.0.0
  extended_image: ^7.0.2
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^4.1.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.12
  provider: ^6.0.5
  quiver: ^3.2.1
  responsive_framework: ^0.2.0
  scroll_to_index: ^3.0.1
  table_calendar: ^3.0.8
  url_launcher: ^6.1.9
  visibility_detector: ^0.3.3

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  elementary_test: ^1.1.3
  # flutter_native_splash: ^2.2.17
  # flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  surf_lint_rules: ^1.5.0

# flutter_icons:
#   android: "ic_launcher"
#   ios: false
#   image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/calendar/
    - assets/nav_bar/

  fonts:
    - family: HelveticaNeueCyr
      fonts:
        - asset: fonts/HelveticaNeueCyr-Light.ttf

    - family: HelveticaNeueCyr-Bold
      fonts:
        - asset: fonts/HelveticaNeueCyr-Bold.ttf

    - family: HelveticaNeueCyr-Medium
      fonts:
        - asset: fonts/HelveticaNeueCyr-Medium.ttf

    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter-Regular.ttf
