import 'package:f1_pet_project/common/repositories/espn/espn_media_repository.dart';
import 'package:f1_pet_project/common/repositories/espn/espn_scoreboard_repository.dart';
import 'package:f1_pet_project/common/repositories/seasons/seasons_repository.dart';
import 'package:f1_pet_project/common/repositories/wikipedia/wikipedia_page_image_repository.dart';
import 'package:f1_pet_project/core/circuits/repositories/circuits_repository.dart';
import 'package:f1_pet_project/core/circuits/stats/circuit_stats_repository.dart';
import 'package:f1_pet_project/core/home/repositories/current_standings_repository.dart';
import 'package:f1_pet_project/core/news/repositories/news_repository.dart';
import 'package:f1_pet_project/core/predictor/repositories/predictor_leaderboard_repository.dart';
import 'package:f1_pet_project/core/predictor/repositories/predictor_repository.dart';
import 'package:f1_pet_project/core/results/constructor/repositories/constructor_career_repository.dart';
import 'package:f1_pet_project/core/results/constructor/repositories/constructor_catalog_repository.dart';
import 'package:f1_pet_project/core/results/driver/repositories/driver_career_repository.dart';
import 'package:f1_pet_project/core/results/driver/repositories/driver_catalog_repository.dart';
import 'package:f1_pet_project/core/results/finish_status/repositories/finish_status_repository.dart';
import 'package:f1_pet_project/core/results/h2h/repositories/h2h_repository.dart';
import 'package:f1_pet_project/core/results/hall_of_fame/repositories/season_standings_repository.dart';
import 'package:f1_pet_project/core/results/repositories/race_weekend_repository.dart';
import 'package:f1_pet_project/core/results/repositories/results_repository.dart';
import 'package:f1_pet_project/core/schedule/repositories/schedule_repository.dart';
import 'package:f1_pet_project/services/analytics/analytics_gateway.dart';
import 'package:f1_pet_project/services/app_data_refresh.dart';
import 'package:f1_pet_project/services/auth/auth_service.dart';
import 'package:f1_pet_project/services/firebase/remote_config_service.dart';
import 'package:f1_pet_project/services/home_widget/app_widget_sync_service.dart';
import 'package:f1_pet_project/services/notifications/race_reminder_service.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Root DI providers — override with real instances in `main`.
Never _mustOverride() => throw UnsupportedError('Override this provider in main / tests');

final scheduleRepositoryProvider = Provider<ScheduleRepository>((ref) => _mustOverride());
final seasonsRepositoryProvider = Provider<SeasonsRepository>((ref) => _mustOverride());
final circuitStatsRepositoryProvider = Provider<CircuitStatsRepository>((ref) => _mustOverride());
final currentStandingsRepositoryProvider = Provider<CurrentStandingsRepository>((ref) => _mustOverride());
final resultsRepositoryProvider = Provider<ResultsRepository>((ref) => _mustOverride());
final raceWeekendRepositoryProvider = Provider<RaceWeekendRepository>((ref) => _mustOverride());
final circuitsRepositoryProvider = Provider<CircuitsRepository>((ref) => _mustOverride());
final seasonStandingsRepositoryProvider = Provider<SeasonStandingsRepository>((ref) => _mustOverride());
final finishStatusRepositoryProvider = Provider<FinishStatusRepository>((ref) => _mustOverride());
final h2hRepositoryProvider = Provider<H2hRepository>((ref) => _mustOverride());
final driverCareerRepositoryProvider = Provider<DriverCareerRepository>((ref) => _mustOverride());
final constructorCareerRepositoryProvider = Provider<ConstructorCareerRepository>((ref) => _mustOverride());
final driverCatalogRepositoryProvider = Provider<DriverCatalogRepository>((ref) => _mustOverride());
final constructorCatalogRepositoryProvider = Provider<ConstructorCatalogRepository>((ref) => _mustOverride());
final authServiceProvider = Provider<AuthService>((ref) => _mustOverride());
final predictorRepositoryProvider = Provider<PredictorRepository>((ref) => _mustOverride());
final predictorLeaderboardRepositoryProvider = Provider<PredictorLeaderboardRepository>((ref) => _mustOverride());
final espnScoreboardRepositoryProvider = Provider<EspnScoreboardRepository>((ref) => _mustOverride());
final newsRepositoryProvider = Provider<NewsRepository>((ref) => _mustOverride());
final espnMediaRepositoryProvider = Provider<EspnMediaRepository>((ref) => _mustOverride());
final wikipediaPageImageRepositoryProvider = Provider<WikipediaPageImageRepository>((ref) => _mustOverride());
final appDataRefreshProvider = Provider<AppDataRefresh>((ref) => _mustOverride());
final analyticsGatewayProvider = Provider<AnalyticsGateway>((ref) => _mustOverride());
final remoteConfigServiceProvider = Provider<RemoteConfigService>((ref) => _mustOverride());
final raceReminderServiceProvider = Provider<RaceReminderService>((ref) => _mustOverride());
final appWidgetSyncServiceProvider = Provider<AppWidgetSyncService>((ref) => _mustOverride());
